"""
Critique resolution module to arbitrate disagreements from a previous debate round.
This script reads critique data from multiple files generated by a previous process.
For each sentence where the chosen critiques differ, it uses a model to analyze the
reasoning from the previous round and produce a single, final critique.
"""

import json
import sys
import re
from tqdm import tqdm
from prompts import CRITIQUE_DEBATE_PROMPT
from model import Model


def format_agent_answers(verifications):
    """Format agent answers for debate prompt"""
    formatted_answers = []
    for i, verification in enumerate(verifications):
        if verification and "answer" in verification and "reasoning" in verification:
            answer = verification["answer"]
            reasoning = verification["reasoning"].strip()
            
            # Clean up reasoning
            for prefix in ["no.", "no,", "no", "yes.", "yes,", "yes"]:
                if reasoning.lower().startswith(prefix):
                    reasoning = reasoning[len(prefix):].strip()
                    break
            
            if reasoning:
                reasoning = reasoning[0].upper() + reasoning[1:]
            
            formatted_answers.append(
                f"Agent {i+1}'s answer: {{\"reasoning\": {reasoning}, \"answer\": {answer}}}"
            )
    
    return "\n".join(formatted_answers)

def resolve_disagreement(model, topic, document, sentence, critique1, critique2, agent_answers_str, max_retries=3):
    """
    Resolves a disagreement using the detailed debate prompt.
    This function now expects the model to return a choice ('1' or '2').
    """
    prompt = CRITIQUE_DEBATE_PROMPT.format(
        topic=topic,
        document=document,
        summary=sentence, # The prompt uses 'summary' for the sentence
        response1=critique1,
        response2=critique2,
        agent_answers=agent_answers_str,
    )

    for attempt in range(max_retries):
        try:
            response = model.run(prompt)
            if response is not None:
                json_match = re.search(r"\{.*\}", response, re.DOTALL)
                if not json_match:
                    raise ValueError("No JSON object found in the response")
                
                response_json = json.loads(json_match.group(0))
                answer = str(response_json["answer"])
                
                if answer not in ["1", "2"]:
                    raise ValueError(f"Invalid answer: {answer}. Must be '1' or '2'.")
                
                return {"answer": int(answer), "reasoning": response_json["reasoning"]}

        except (ValueError, KeyError, json.JSONDecodeError) as e:
            print(f"Attempt {attempt + 1} failed for sentence. Error: {e}. Retrying...")
            if attempt == max_retries - 1:
                print("Max retries reached. Failing for this sentence.")
                return None
    return None

def generate_resolved_critiques(model_name, data_files, output_file, api_key=None):
    """
    Main function to process and resolve disagreements from a previous critique selection round.
    """
    try:
        data_all = [json.load(open(file)) for file in data_files]
        if not data_all:
            raise ValueError("No data files were provided or loaded.")
    except Exception as e:
        print(f"Error loading data files: {e}")
        sys.exit(1)

    model = Model(model_name, api_key)
    base_data = data_all[0]
    results = []
    
    for i, item in enumerate(tqdm(base_data, desc="Processing items")):
        # (item setup remains the same)
        document = item["document"]
        summary_sentences = item.get("summary_sentences", [])
        topic = item.get("topic", "Unknown")

        critique_resolutions = []
        critique_finals_resolved = []

        if summary_sentences:
            for j, sentence in enumerate(tqdm(summary_sentences, desc="Processing sentences", leave=False)):
                previous_outcomes = []
                team_answer_choices = set()
                critiques_originals = [data_source[i]["critique"][j] for data_source in data_all]
                team_answers = [data_source[i]["critique_team_answer"][j] for data_source in data_all]

                for data_source in data_all:
                    try:
                        critique_final = data_source[i]["critique_final"][j]
                        team_answer = data_source[i]["critique_team_answer"][j]
                        
                        if critique_final:
                            choice = team_answer.get("answer") if team_answer else None
                            team_answer_choices.add(choice)
                            reasoning = team_answer.get("reasoning", "N/A (unanimous choice)") if team_answer else "N/A (unanimous choice)"
                            previous_outcomes.append({"answer": critique_final, "reasoning": reasoning})
                            
                    except (IndexError, KeyError, TypeError):
                        continue
                
                resolution = None
                final_critique = None
                # Only debate if the team_answer choices from the previous round differ.
                if len(team_answer_choices) > 1:
                    unique_outcomes = list({outcome['answer']: outcome for outcome in previous_outcomes}.values())
                    
                    critique1 = critiques_originals[0]
                    critique2 = critiques_originals[1]
                        
                    agent_answers_str = format_agent_answers(team_answers)
                    
                    resolution = resolve_disagreement(
                        model, topic, document, sentence, critique1, critique2, agent_answers_str
                    )
                    
                    if resolution and "answer" in resolution:
                        # Select the final critique based on the model's new choice
                        chosen_index = resolution["answer"] - 1
                        final_critique = [critique1, critique2][chosen_index]
                
                elif previous_outcomes:
                    # If no disagreement in choices, use the consensus answer
                    final_critique = previous_outcomes[0]["answer"]

                critique_resolutions.append(resolution)
                critique_finals_resolved.append(final_critique)

        item["critique_team_answer"] = critique_resolutions
        item["critique_final"] = critique_finals_resolved
        results.append(item)
    
    with open(output_file, 'w') as f:
        json.dump(results, f, indent=2)
    
    print(f"Critique resolution complete. Final results saved to {output_file}")

if __name__ == "__main__":
    if len(sys.argv) < 4:
        print("Usage: python resolve_critique.py <model_name> <round1_file_1.json> <round1_file_2.json> ... <final_output_file.json>")
        print("Example: python resolve_critique.py gpt-4-turbo round1_output_A.json round1_output_B.json final_resolved_critiques.json")
        sys.exit(1)
    
    model_name = sys.argv[1]
    output_file = sys.argv[-1]
    data_files = sys.argv[2:-1]
    
    generate_resolved_critiques(model_name, data_files, output_file)