"""
Refinement resolution module to arbitrate disagreements from a previous debate round.
This script reads refinement data from multiple files generated by a previous process.
For each item where the chosen refined summaries differ, it uses a model to analyze the
reasoning from the previous round and produce a single, final summary.
"""

import json
import sys
import re
from tqdm import tqdm
from prompts import REFINEMENT_DEBATE_PROMPT
from model import Model

def format_agent_answers(verifications):
    """Format agent answers for debate prompt"""
    formatted_answers = []
    for i, verification in enumerate(verifications):
        if verification and "answer" in verification and "reasoning" in verification:
            answer = verification["answer"]
            reasoning = verification["reasoning"].strip()
            
            # Clean up reasoning
            for prefix in ["no.", "no,", "no", "yes.", "yes,", "yes"]:
                if reasoning.lower().startswith(prefix):
                    reasoning = reasoning[len(prefix):].strip()
                    break
            
            if reasoning:
                reasoning = reasoning[0].upper() + reasoning[1:]
            
            formatted_answers.append(
                f"Agent {i+1}'s answer: {{\"reasoning\": {reasoning}, \"answer\": {answer}}}"
            )
    
    return "\n".join(formatted_answers)

def resolve_disagreement(model, topic, document, summary1, summary2, agent_answers_str, max_retries=3):
    """
    Resolves a disagreement on the best summary using a detailed debate prompt.
    This function expects the model to return a choice ('1' or '2') and reasoning.
    
    Args:
        model (Model): The language model instance.
        topic (str): The topic of the document.
        document (str): The source document.
        summary1 (str): The first summary option.
        summary2 (str): The second summary option.
        agent_answers_str (str): Formatted string of the previous round's reasoning.
        max_retries (int): The maximum number of retries in case of an error.
        
    Returns:
        dict or None: A dictionary with the new 'answer' and 'reasoning', or None on failure.
    """
    prompt = REFINEMENT_DEBATE_PROMPT.format(
        topic=topic,
        document=document,
        response1=summary1,
        response2=summary2,
        agent_answers=agent_answers_str,
    )

    for attempt in range(max_retries):
        try:
            response = model.run(prompt)
            
            if response is not None:
                json_match = re.search(r"\{.*\}", response, re.DOTALL)
                if not json_match:
                    raise ValueError("No JSON object found in the response")
                
                response_json = json.loads(json_match.group(0))
                answer = str(response_json["answer"])
                
                if answer not in ["1", "2"]:
                    raise ValueError(f"Invalid answer: {answer}. Must be '1' or '2'.")
                
                return {"answer": int(answer), "reasoning": response_json["reasoning"]}

        except (ValueError, KeyError, json.JSONDecodeError) as e:
            print(f"Attempt {attempt + 1} failed for item. Error: {e}. Retrying...")
            if attempt == max_retries - 1:
                print("Max retries reached. Failing for this item.")
                return None
    return None

def generate_resolved_refinements(model_name, data_files, output_file, api_key=None):
    """
    Main function to process and resolve disagreements from a previous refinement selection round.
    
    Args:
        model_name (str): The name of the model to use for the debate.
        data_files (list): A list of file paths for the JSON inputs from the previous round.
        output_file (str): The path to save the final resolved JSON output.
        api_key (str, optional): The API key for the model service.
    """
    try:
        data_all = [json.load(open(file)) for file in data_files]
        if not data_all:
            raise ValueError("No data files were provided or loaded.")
    except Exception as e:
        print(f"Error loading data files: {e}")
        sys.exit(1)

    model = Model(model_name, api_key)
    base_data = data_all[0]
    results = []
    
    for i, item in enumerate(tqdm(base_data, desc="Processing refined summaries")):
        document = item["document"]
        topic = item.get("topic", "Unknown")

        # --- Data Collection from Previous Round ---
        # Get the final summaries chosen by each team in the last round
        final_summaries_from_teams = [data_source[i].get("refined_summary_final") for data_source in data_all]
        
        # Get the reasoning provided by each team in the last round
        team_answers = [data_source[i].get("refined_summary_team_answer") for data_source in data_all]
        team_answers_set = set([answer["answer"] for answer in team_answers if answer])
        
        # Get the original summary candidates from the first team's file (assuming they are the same)
        # This is needed in case of a debate.
        refinement_original = [data_source[i]["refined_summary"] for data_source in data_all]

        # Use a set to easily check if there was a disagreement in the final summaries chosen.
        team_summary_choices = set(s for s in final_summaries_from_teams if s)

        resolution = None
        final_summary = None

        print(final_summaries_from_teams)
        print(team_answers)
        print(team_summary_choices)

        # --- Disagreement Resolution ---
        if len(team_answers_set) > 1:
            # There is a disagreement; a debate is needed.
            summary1, summary2 = refinement_original[0], refinement_original[1]
            
            # Format the reasoning from the previous round to be used in the debate prompt
            agent_answers_str = format_agent_answers(team_answers)
            
            # Call the model to resolve the disagreement
            resolution = resolve_disagreement(
                model, topic, document, summary1, summary2, agent_answers_str
            )
            
            if resolution and "answer" in resolution:
                # Select the final summary based on the model's new choice
                chosen_index = resolution["answer"] - 1
                final_summary = [summary1, summary2][chosen_index]
            else:
                # Fallback to the first summary if the debate fails
                final_summary = summary1
        
        elif team_summary_choices:
            # All teams agreed in the previous round, so no debate is needed.
            final_summary = list(team_summary_choices)[0]

        # Update the item with the results of this resolution round
        item["refined_summary_team_answer"] = resolution
        item["refined_summary_final"] = final_summary
        results.append(item)
    
    # --- Save Final Results ---
    with open(output_file, 'w') as f:
        json.dump(results, f, indent=2)
    
    print(f"Refinement resolution complete. Final results saved to {output_file}")

if __name__ == "__main__":
    if len(sys.argv) < 4:
        print("Usage: python resolve_refine.py <model_name> <round1_file_1.json> <round1_file_2.json> ... <final_output_file.json>")
        print("Example: python resolve_refine.py gpt-4-turbo round1_output_A.json round1_output_B.json final_resolved_refinements.json")
        sys.exit(1)
    
    model_name = sys.argv[1]
    output_file = sys.argv[-1]
    data_files = sys.argv[2:-1]
    
    generate_resolved_refinements(model_name, data_files, output_file)